/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProducerWorkArea;

import business.organization.ManufacturingOrganization;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saloni
 */
public class ProducerWorkAreaManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProducerWorkAreaManagementJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ManufacturingOrganization organization;
    private UserAccount userAccount;
    private Ecosystem business;

    public ProducerWorkAreaManagementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (ManufacturingOrganization) organization;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton3 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        customizedOrderJButton1 = new javax.swing.JButton();
        customizedOrderJButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton3.setBackground(new java.awt.Color(255, 204, 204));
        backJButton3.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton3.setForeground(new java.awt.Color(102, 0, 51));
        backJButton3.setText("Back");
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 6, -1, 36));

        enterpriseLabel.setBackground(new java.awt.Color(255, 204, 204));
        enterpriseLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 48, 110, 30));

        enterpriseLabel1.setBackground(new java.awt.Color(255, 204, 204));
        enterpriseLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 84, -1, 26));

        orgValueLabel.setBackground(new java.awt.Color(255, 204, 204));
        orgValueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        orgValueLabel.setForeground(new java.awt.Color(102, 0, 51));
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 84, 87, 26));

        valueLabel.setBackground(new java.awt.Color(255, 204, 204));
        valueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 0, 51));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 50, 90, 26));

        customizedOrderJButton1.setBackground(new java.awt.Color(255, 204, 204));
        customizedOrderJButton1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        customizedOrderJButton1.setForeground(new java.awt.Color(102, 0, 51));
        customizedOrderJButton1.setText("Customised Orders Work Requests");
        customizedOrderJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedOrderJButton1ActionPerformed(evt);
            }
        });
        add(customizedOrderJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 360, 70));

        customizedOrderJButton2.setBackground(new java.awt.Color(255, 204, 204));
        customizedOrderJButton2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        customizedOrderJButton2.setForeground(new java.awt.Color(102, 0, 51));
        customizedOrderJButton2.setText("Inventory Work Requests");
        customizedOrderJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedOrderJButton2ActionPerformed(evt);
            }
        });
        add(customizedOrderJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 360, 70));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProducerWorkArea/factory.gif"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 430, 334));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProducerWorkArea/package.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 431, 390, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void customizedOrderJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedOrderJButton1ActionPerformed
        // TODO add your handling code here:
        ProducerWorkRequestsJPanel manufactureJPanel = new ProducerWorkRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanel", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customizedOrderJButton1ActionPerformed

    private void customizedOrderJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedOrderJButton2ActionPerformed
        RequestsFromInventoryWRJPanel manufactureJPanel = new RequestsFromInventoryWRJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanelNew", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customizedOrderJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JButton customizedOrderJButton1;
    private javax.swing.JButton customizedOrderJButton2;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
