/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProducerWorkArea;

import Business.WorkQueue.InventoryWorkRequest;
import business.enterprise.Enterprise;
import business.organization.InventoryOrganization;
import business.organization.ManufacturingOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrunalbhalerao
 */
public class RequestInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestInventoryJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ManufacturingOrganization organization;
    
    public RequestInventoryJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Organization organization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = (ManufacturingOrganization) organization;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        itemCountJTextField = new javax.swing.JTextField();
        requestInventoryJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        itemNameJTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 113, -1, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        orgValueLabel.setForeground(new java.awt.Color(102, 0, 51));
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 154, 230, 26));

        valueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 0, 51));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 115, 210, 26));

        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 103, 39));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Item Count");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        itemCountJTextField.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        itemCountJTextField.setForeground(new java.awt.Color(102, 0, 51));
        itemCountJTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(itemCountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 194, 37));

        requestInventoryJButton.setBackground(new java.awt.Color(255, 255, 255));
        requestInventoryJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        requestInventoryJButton.setForeground(new java.awt.Color(102, 0, 51));
        requestInventoryJButton.setText("Send Inventory Request");
        requestInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestInventoryJButtonActionPerformed(evt);
            }
        });
        add(requestInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 250, 50));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Item Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        itemNameJTextField1.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        itemNameJTextField1.setForeground(new java.awt.Color(102, 0, 51));
        itemNameJTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(itemNameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 194, 37));

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel3.setText("The Cloth Factory");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/start page.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 516, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProducerWorkRequestsJPanel dwjp = (ProducerWorkRequestsJPanel) component;
        dwjp.populateDesignerWorkRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestInventoryJButtonActionPerformed

        String itemCount = itemCountJTextField.getText();
        String itemName = itemNameJTextField1.getText();
        InventoryWorkRequest request = new InventoryWorkRequest();
        
        if (itemCount.matches("[0-9]+")) {
            request.setItemCount(Integer.parseInt(itemCount));
        } else {
            JOptionPane.showMessageDialog(null, "Item count has to be a number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (itemName.matches("[a-zA-Z]+")) {
            request.setItemName(itemName);
        } else {
            JOptionPane.showMessageDialog(null, "Item name has to be a string", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setManufacturerSenderInv(userAccount);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);

        }
        JOptionPane.showMessageDialog(null, "Inventory Request sent to Inventory Staff", "Info", JOptionPane.INFORMATION_MESSAGE);
        itemCountJTextField.setText("");
        itemNameJTextField1.setText("");
    }//GEN-LAST:event_requestInventoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JTextField itemCountJTextField;
    private javax.swing.JTextField itemNameJTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton requestInventoryJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
