/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QualityControlManagerWorkArea;

import Business.WorkQueue.QualityControlWorkRequest;
import business.organization.QualityControlOrganization;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.productionEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.ReportOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saloni
 */
public class QualityControlManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QualityControlManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private Ecosystem business;
    
    public QualityControlManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (QualityControlOrganization) organization;
        this.userAccount = account;
        this.business = business;
        
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        btnRequestReport = new javax.swing.JButton();
        btnFetchReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 127, 20));

        enterpriseLabel1.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setForeground(new java.awt.Color(102, 0, 51));
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 120, 130, -1));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 0, 51));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 84, 130, -1));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 103, 26));

        btnRequestReport.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestReport.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        btnRequestReport.setForeground(new java.awt.Color(102, 0, 51));
        btnRequestReport.setText("Request Report");
        btnRequestReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestReportActionPerformed(evt);
            }
        });
        add(btnRequestReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 500, 90));

        btnFetchReports.setBackground(new java.awt.Color(255, 255, 255));
        btnFetchReports.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        btnFetchReports.setForeground(new java.awt.Color(102, 0, 51));
        btnFetchReports.setText("Fetch Quality Reports");
        btnFetchReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchReportsActionPerformed(evt);
            }
        });
        add(btnFetchReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 500, 90));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QualityControlManagerWorkArea/dog.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 125, 298, 318));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnRequestReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestReportActionPerformed
        //request sent to regulatory
        QualityControlWorkRequest rwr = new QualityControlWorkRequest();
        rwr.setStatus("Report Requested");
        rwr.setSender(userAccount);
        String reportType = "Hazardous Content";
        rwr.setReportType(reportType);
        //adding work request to the reporting organization work queue
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof productionEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ReportOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(rwr);
                        }
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Report requested to Reporting", "Info", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnRequestReportActionPerformed

    private void btnFetchReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchReportsActionPerformed
        //reports generated with the regulatory
        File file = new File("/Users/mrunalbhalerao/NetBeansProjects/AED_Final_Project/AED_final/src/QualityControlManagerWorkArea/Report.csv");
        float content1 = 0;
        float content2 = 0;
        float content3 = 0;
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof productionEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ReportOrganization) {

                           content1 = ((ReportOrganization) organization).getReport().getCumCarbonEmission();
                           content2 = ((ReportOrganization) organization).getReport().getCumWaterToxin();
                           content3 = ((ReportOrganization) organization).getReport().getCumWaste();

                        }
                    }
                }
            }
        }

        String content = "Hazardous Components Reports is as follows:" + 
                "Carbon Emmision Content:" + " " + content1 + " " + "Water Toxin Content:" + " " + content2 + " " + "Waste Content:" + " " + content3;

        try (FileOutputStream fop = new FileOutputStream(file)) {

            // if file doesn't exists, then create it
            if (!file.exists()) {
                file.createNewFile();
            }

            // get the content in bytes
            byte[] contentInBytes = content.getBytes();

            fop.write(contentInBytes);
            fop.flush();
            fop.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "Report downloaded", "Info", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFetchReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnFetchReports;
    private javax.swing.JButton btnRequestReport;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
