/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import Business.WorkQueue.OrderOnlineWorkRequest;
import Business.customer.ClothFactoryCatalog;
import Business.customer.ClothFactoryOrderItem;
import Business.customer.ClothFactoryProduct;
import business.organization.CustomerOrganization;
import Business.customer.MasterOrderList;
import Business.customer.OrderOnline;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.customerCareEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalbhalerao
 */
public class BuyOnlineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyOnlineJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    
    public BuyOnlineJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
    
    OrderOnline oo = new OrderOnline();
    ClothFactoryOrderItem cfo = new ClothFactoryOrderItem();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclothfactory = new javax.swing.JTable();
        placeOrderJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton2.setForeground(new java.awt.Color(102, 0, 51));
        backJButton2.setText("Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        tblclothfactory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tblclothfactory.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        tblclothfactory.setForeground(new java.awt.Color(102, 0, 51));
        tblclothfactory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apparel ID", "Brand", "Model Number", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblclothfactory);
        if (tblclothfactory.getColumnModel().getColumnCount() > 0) {
            tblclothfactory.getColumnModel().getColumn(0).setResizable(false);
            tblclothfactory.getColumnModel().getColumn(1).setResizable(false);
            tblclothfactory.getColumnModel().getColumn(2).setResizable(false);
            tblclothfactory.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 590, 350));

        placeOrderJButton.setBackground(new java.awt.Color(255, 255, 255));
        placeOrderJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        placeOrderJButton.setForeground(new java.awt.Color(102, 0, 51));
        placeOrderJButton.setText("Place Order");
        placeOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderJButtonActionPerformed(evt);
            }
        });
        add(placeOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 197, 43));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 435, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/order (1).gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 198, 192));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/ordernow (1).gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 204, 135));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblclothfactory.getModel();
        dtm.setRowCount(0);
        for (Organization storeOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (storeOrganization instanceof StoreOrganization) {
                ClothFactoryCatalog cccat = ((StoreOrganization) storeOrganization).getCfc();

                for (ClothFactoryProduct cfp : cccat.getListOfClothFactoryProduct()) {
                    Object[] row = new Object[4];
                    row[0] = cfp;
                    row[1] = cfp.getBrand();
                    row[2] = cfp.getModelNumber();
                    row[3] = cfp.getPrice();
                    dtm.addRow(row);
                    System.out.println(cfp.getBrand());
                }
            }
        }
    }
    
    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void placeOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderJButtonActionPerformed
        int selectedRow = tblclothfactory.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        ClothFactoryProduct cc = (ClothFactoryProduct) tblclothfactory.getValueAt(selectedRow, 0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof customerCareEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {
                            mod = ((StoreOrganization) organization).getMol();
                        }

                    }
                }
            }
        }
        
        cfo = oo.addClothOrderItem();
        cfo.setClothFactoryProduct(cc);
        oo.setCustomer(account.getEmployee());

        mod.addOnlineOrder(oo);

        OrderOnlineWorkRequest orderAtStoreWR = new OrderOnlineWorkRequest();
        orderAtStoreWR.setOrderOnline(oo);
        orderAtStoreWR.setStatus("Placed");
        orderAtStoreWR.setSender(account);
        account.getWorkQueue().getWorkRequestList().add(orderAtStoreWR);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof StoreOrganization) {
                organization.getWorkQueue().getWorkRequestList().add(orderAtStoreWR);
            }
        }

        JOptionPane.showMessageDialog(null, "Order Placed Successfully", "Information!!", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_placeOrderJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeOrderJButton;
    private javax.swing.JTable tblclothfactory;
    // End of variables declaration//GEN-END:variables
}
