/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import Business.WorkQueue.CustomerCustomizedWorkRequest;
import Business.WorkQueue.OrderOnlineWorkRequest;
import business.organization.CustomerOrganization;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Your Name <your.name at your.org>
 */
public class CustomerOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrdersJPanel
     */
    private JPanel userProcessContainer;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    
    public CustomerOrdersJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
       
        customerName.setText(account.getUsername());

        populateCustomerTable();
        populateStoreOrdersTable();
    }
    
    public void populateCustomerTable() {
        DefaultTableModel model = (DefaultTableModel) customisedOrderJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof CustomerCustomizedWorkRequest) {
                Object[] row = new Object[4];
                CustomerCustomizedWorkRequest cw = (CustomerCustomizedWorkRequest) wr;
                row[0] = cw;
                row[1] = cw.getStoreSender() == null ? null : cw.getStoreSender().getEmployee().getName();
                row[2] = cw.getRequestDate();
                row[3] = cw.getStatus();
                model.addRow(row);
            }

        }
    }

    public void populateStoreOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) onlineOrdersJTable.getModel();

        model.setRowCount(0);
        {
            for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
                if (wr instanceof OrderOnlineWorkRequest) {
                    Object[] row = new Object[4];
                    OrderOnlineWorkRequest oas = (OrderOnlineWorkRequest) wr;
                    row[0] = oas;
                    row[1] = oas.getSender().getEmployee().getName();
                    row[2] = oas.getRequestDate();
                    row[3] = oas.getStatus();
                    model.addRow(row);

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        customerOrdersjProgressBar = new javax.swing.JProgressBar();
        checkOrderStatusJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customisedOrderJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlineOrdersJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, 24));

        jLabel8.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Hello!");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 93, -1, -1));

        refreshJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(102, 0, 51));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 125, 28));

        customerOrdersjProgressBar.setBackground(new java.awt.Color(255, 153, 153));
        customerOrdersjProgressBar.setForeground(new java.awt.Color(102, 0, 51));
        customerOrdersjProgressBar.setStringPainted(true);
        add(customerOrdersjProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 170, -1));

        checkOrderStatusJButton.setBackground(new java.awt.Color(204, 204, 255));
        checkOrderStatusJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        checkOrderStatusJButton.setForeground(new java.awt.Color(102, 0, 51));
        checkOrderStatusJButton.setText("Check Order Status");
        checkOrderStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOrderStatusJButtonActionPerformed(evt);
            }
        });
        add(checkOrderStatusJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Customized Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 320, 60));

        customisedOrderJTable.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        customisedOrderJTable.setForeground(new java.awt.Color(102, 0, 51));
        customisedOrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Sender", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customisedOrderJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 840, 180));

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Online Orders");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 290, 60));

        onlineOrdersJTable.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        onlineOrdersJTable.setForeground(new java.awt.Color(102, 0, 51));
        onlineOrdersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Sender", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(onlineOrdersJTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 840, 190));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 360, 60));

        customerName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(102, 0, 51));
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateCustomerTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void checkOrderStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOrderStatusJButtonActionPerformed
        //  progress bar used to check the order status
        int selectedRow = customisedOrderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row to check progress", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            CustomerCustomizedWorkRequest cw = (CustomerCustomizedWorkRequest) customisedOrderJTable.getValueAt(selectedRow, 0);
            if (cw.getStatus().equalsIgnoreCase("Placed")) {
                customerOrdersjProgressBar.setValue(15);
            } else if (cw.getStatus().equalsIgnoreCase("Order Final")) {
                customerOrdersjProgressBar.setValue(30);
            } else if (cw.getStatus().equalsIgnoreCase("Design Order")) {
                customerOrdersjProgressBar.setValue(50);
            } else if (cw.getStatus().equalsIgnoreCase("Manufacture Order")) {
                customerOrdersjProgressBar.setValue(65);
            } else if (cw.getStatus().equalsIgnoreCase("Manufactured")) {
                customerOrdersjProgressBar.setValue(70);
            } else if (cw.getStatus().equalsIgnoreCase("Order Completed")) {
                customerOrdersjProgressBar.setValue(80);
            } else if (cw.getStatus().equalsIgnoreCase("Order Ready")) {
                customerOrdersjProgressBar.setValue(100);
            }

        }
    }//GEN-LAST:event_checkOrderStatusJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton checkOrderStatusJButton;
    private javax.swing.JLabel customerName;
    private javax.swing.JProgressBar customerOrdersjProgressBar;
    private javax.swing.JTable customisedOrderJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable onlineOrdersJTable;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
