/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerWorkArea;

import Business.WorkQueue.CustomerCustomizedWorkRequest;
import Business.customer.MasterOrderList;
import Business.customer.PersonalisedOrder;
import Business.customer.PersonalisedOrderItem;
import business.organization.CustomerOrganization;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.customerCareEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saloni
 */
public class CustomerWorkAreaManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaManagementJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private PersonalisedOrder order;
    private CustomerOrganization customerOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem business;
    
    public CustomerWorkAreaManagementJPanel(JPanel userProcessContainer, MasterOrderList mod, PersonalisedOrder order, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.mod = mod;
        this.order = order;
        this.customerOrganization = (CustomerOrganization) organization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        customerName1.setText(userAccount.getUsername());
        
        populateTable();
    }
    
    private void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) customerCartjTable.getModel();
        dtm.setRowCount(0);

        for (PersonalisedOrderItem oi : order.getOrderItemList()) {
            Object[] row = new Object[2];
            row[0] = oi;
            row[1] = oi.getPersonaliseProduct().getPrice();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerCartjTable = new javax.swing.JTable();
        viewDetailjBtn = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        placeOrderjBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerName1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 20, 101, -1));

        jLabel8.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Hello!");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        customerCartjTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerCartjTable.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        customerCartjTable.setForeground(new java.awt.Color(102, 0, 5));
        customerCartjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Item Id", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerCartjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 620, 220));

        viewDetailjBtn.setBackground(new java.awt.Color(204, 204, 255));
        viewDetailjBtn.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        viewDetailjBtn.setForeground(new java.awt.Color(102, 0, 51));
        viewDetailjBtn.setText("View Details");
        viewDetailjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjBtnActionPerformed(evt);
            }
        });
        add(viewDetailjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        deletejButton.setBackground(new java.awt.Color(204, 204, 255));
        deletejButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        deletejButton.setForeground(new java.awt.Color(102, 0, 51));
        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 160, -1));

        placeOrderjBtn.setBackground(new java.awt.Color(204, 204, 255));
        placeOrderjBtn.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        placeOrderjBtn.setForeground(new java.awt.Color(102, 0, 51));
        placeOrderjBtn.setText("Place Order");
        placeOrderjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderjBtnActionPerformed(evt);
            }
        });
        add(placeOrderjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 170, -1));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 17, 340, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreManagerWorkArea/blossoms.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        customerName1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        customerName1.setForeground(new java.awt.Color(102, 0, 51));
        add(customerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewDetailjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        PersonalisedOrderItem oi = (PersonalisedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
        ViewOrderDetailsJPanel vjp = new ViewOrderDetailsJPanel(userProcessContainer, oi);
        userProcessContainer.add("SupplierWorkAreaJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewDetailjBtnActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to delete data", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            PersonalisedOrderItem oi = (PersonalisedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
            order.removeOrderItem(oi);
            populateTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void placeOrderjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderjBtnActionPerformed

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //mod.addOrderFromInput(order);

        CustomerCustomizedWorkRequest cworkrequest = new CustomerCustomizedWorkRequest();
        cworkrequest.setOrder(order);
        cworkrequest.setStatus("Placed");
        cworkrequest.setCustomerSender(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(cworkrequest);

        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof customerCareEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {

                            organization.getWorkQueue().getWorkRequestList().add(cworkrequest);

                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Order Placed Successfully", "Information!!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_placeOrderjBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable customerCartjTable;
    private javax.swing.JLabel customerName1;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeOrderjBtn;
    private javax.swing.JButton viewDetailjBtn;
    // End of variables declaration//GEN-END:variables
}
