/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import business.organization.CustomerOrganization;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mrunalbhalerao
 */
public class CustomerMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMainJPanel
     */
    private JPanel userProcessContainer;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    public CustomerMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizejBtn = new javax.swing.JButton();
        buyOnlinejBtn = new javax.swing.JButton();
        customerOrdersJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customizejBtn.setBackground(new java.awt.Color(255, 255, 255));
        customizejBtn.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        customizejBtn.setForeground(new java.awt.Color(102, 0, 51));
        customizejBtn.setText("Customize");
        customizejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizejBtnActionPerformed(evt);
            }
        });
        add(customizejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 370, 60));

        buyOnlinejBtn.setBackground(new java.awt.Color(255, 255, 255));
        buyOnlinejBtn.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        buyOnlinejBtn.setForeground(new java.awt.Color(102, 0, 51));
        buyOnlinejBtn.setText("Buy Online");
        buyOnlinejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyOnlinejBtnActionPerformed(evt);
            }
        });
        add(buyOnlinejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 370, 60));

        customerOrdersJButton.setBackground(new java.awt.Color(255, 255, 255));
        customerOrdersJButton.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        customerOrdersJButton.setForeground(new java.awt.Color(102, 0, 51));
        customerOrdersJButton.setText("Requested Orders");
        customerOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerOrdersJButtonActionPerformed(evt);
            }
        });
        add(customerOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 370, 70));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 330, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/customise (1).gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 180, 414));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/storefinal (1).gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 299, 272));
    }// </editor-fold>//GEN-END:initComponents

    private void customizejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizejBtnActionPerformed

        // TODO add your handling code here:
        System.out.println("reached here");
        PersonalizeJPanel cjp = new PersonalizeJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
        userProcessContainer.add("CustomizeJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        //System.out.println("reached here 2");

    }//GEN-LAST:event_customizejBtnActionPerformed

    private void buyOnlinejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyOnlinejBtnActionPerformed
        //  TODO add your handling code here:
        BuyOnlineJPanel cjp = new BuyOnlineJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
        userProcessContainer.add("BuyAtStoreJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buyOnlinejBtnActionPerformed

    private void customerOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerOrdersJButtonActionPerformed
        //  TODO add your handling code here:
        CustomerOrdersJPanel cjp = new CustomerOrdersJPanel(userProcessContainer, account, customerOrganization, enterprise, business);
        userProcessContainer.add("CustomerOrdersJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customerOrdersJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyOnlinejBtn;
    private javax.swing.JButton customerOrdersJButton;
    private javax.swing.JButton customizejBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
