/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import Business.customer.CustomerApparel;
import Business.customer.PersonalisedOrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mrunalbhalerao
 */
public class ViewOrderDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderDetailsJPanel
     */
    
    private JPanel userProcessContainer;
    private PersonalisedOrderItem orderItem;
    
    public ViewOrderDetailsJPanel(JPanel userProcessContainer, PersonalisedOrderItem orderItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orderItem = orderItem;
        
        CustomerApparel customizeApparel = orderItem.getPersonaliseProduct();
        
        txtCategory.setText(customizeApparel.getCategory());
        txtStyle.setText(customizeApparel.getStyle());
        txtSize.setText(customizeApparel.getColor());
        txtDesignType.setText(customizeApparel.getSize());
        txtTextLocation.setText(customizeApparel.getFabricType());
        txtText.setText(customizeApparel.getPrintText());
        txtQuantity.setText(customizeApparel.getTextLocation());
        txtFabricType.setText(customizeApparel.getDesignTechnique());
        txtColor.setText(customizeApparel.getQuantity());
        txtQuantity.setText(String.valueOf(customizeApparel.getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtStyle = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtFabricType = new javax.swing.JTextField();
        txtText = new javax.swing.JTextField();
        txtTextLocation = new javax.swing.JTextField();
        txtDesignType = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Category");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Color");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 49, -1));

        jLabel4.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("Size");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Fabric Type");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Text");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("Text Location");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 51));
        jLabel9.setText("Design Type");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("Quantity");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jLabel11.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 51));
        jLabel11.setText("Style");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        txtQuantity.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtQuantity.setEnabled(false);
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 150, -1));

        txtCategory.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtCategory.setEnabled(false);
        add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 150, -1));

        txtStyle.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtStyle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtStyle.setEnabled(false);
        add(txtStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 150, -1));

        txtColor.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtColor.setEnabled(false);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 150, -1));

        txtSize.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtSize.setEnabled(false);
        add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 150, -1));

        txtFabricType.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtFabricType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtFabricType.setEnabled(false);
        add(txtFabricType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 150, -1));

        txtText.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtText.setEnabled(false);
        txtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextActionPerformed(evt);
            }
        });
        add(txtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 150, -1));

        txtTextLocation.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtTextLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtTextLocation.setEnabled(false);
        add(txtTextLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 150, -1));

        txtDesignType.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        txtDesignType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtDesignType.setEnabled(false);
        add(txtDesignType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 150, -1));

        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/confirm.gif"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 186, 219));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDesignType;
    private javax.swing.JTextField txtFabricType;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtStyle;
    private javax.swing.JTextField txtText;
    private javax.swing.JTextField txtTextLocation;
    // End of variables declaration//GEN-END:variables
}
