/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ReportManagerWorkArea;

import business.organization.ReportOrganization;
import Business.customer.MasterOrderList;
//import business.customer.MasterOrderList;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.productionEnterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saloni
 */
public class ReportManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportManagerWorkAreaJPanel
     */
    private MasterOrderList mod;
    //private CustomizedOrder customizedOrder;
    //private CustomizedOrderItem customizedOrderItem;
    //private OrderAtStore orderAtStore;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private Organization organization;

    final String applicationTitle = "Hazardous Content Chart";
    final String chartTitle = "Hazardous Content Chart";
    
    public ReportManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (ReportOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton7 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        hazardousContentjBtn = new javax.swing.JButton();
        revenueJButton5 = new javax.swing.JButton();
        workREquestJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton7.setBackground(new java.awt.Color(255, 255, 255));
        backJButton7.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton7.setForeground(new java.awt.Color(102, 0, 51));
        backJButton7.setText("Back");
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });
        add(backJButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, 40));

        enterpriseLabel.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 104, 100, 30));

        enterpriseLabel2.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel2.setText("Organization:");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 144, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        orgValueLabel.setForeground(new java.awt.Color(102, 0, 51));
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 144, 106, 26));

        valueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 0, 51));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 106, 106, 26));

        hazardousContentjBtn.setBackground(new java.awt.Color(255, 255, 255));
        hazardousContentjBtn.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        hazardousContentjBtn.setForeground(new java.awt.Color(102, 0, 51));
        hazardousContentjBtn.setText("Level of Hazardous Content");
        hazardousContentjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hazardousContentjBtnActionPerformed(evt);
            }
        });
        add(hazardousContentjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 233, 270, 80));

        revenueJButton5.setBackground(new java.awt.Color(255, 255, 255));
        revenueJButton5.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        revenueJButton5.setForeground(new java.awt.Color(102, 0, 51));
        revenueJButton5.setText("Revenue ");
        revenueJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueJButton5ActionPerformed(evt);
            }
        });
        add(revenueJButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 412, 270, 80));

        workREquestJButton.setBackground(new java.awt.Color(255, 255, 255));
        workREquestJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        workREquestJButton.setForeground(new java.awt.Color(102, 0, 51));
        workREquestJButton.setText("Work Requests");
        workREquestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workREquestJButtonActionPerformed(evt);
            }
        });
        add(workREquestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 325, 270, 80));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("Organization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 504, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReportManagerWorkArea/reporting.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 233, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel2.setText("The Cloth Factory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed

    private void hazardousContentjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hazardousContentjBtnActionPerformed
        // TODO add your handling code here:

        HazardousContentReportJPanel lcjp = new HazardousContentReportJPanel(userProcessContainer, mod,business);
        userProcessContainer.add("HazardousContentReportJPanel", lcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_hazardousContentjBtnActionPerformed

    private void revenueJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueJButton5ActionPerformed
        // TODO add your handling code here:
        ReportRevenueJPanel rrjp = new ReportRevenueJPanel(userProcessContainer, mod, business);
        userProcessContainer.add("LeadContentReportJPanel", rrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        //            JOptionPane.showMessageDialog(null, customizedRevenue, "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_revenueJButton5ActionPerformed

    private void workREquestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workREquestJButtonActionPerformed

        QualityControlJPanel ojp = new QualityControlJPanel(userProcessContainer,account,organization,enterprise, business);
        userProcessContainer.add("RegulatoryWorkRequests", ojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_workREquestJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReportOfOrganizationJPanel ojp = new ReportOfOrganizationJPanel(userProcessContainer, mod, business);
        userProcessContainer.add("OrganizationReportJPanel", ojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton7;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JButton hazardousContentjBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton revenueJButton5;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton workREquestJButton;
    // End of variables declaration//GEN-END:variables
}
